# Ensemble Inference Configuration

model:
  architecture: "ensemble"
  params:
    models:
      - architecture: "unetr"
        checkpoint: "./outputs/unetr/checkpoints/best_model.pth"
        params:
          in_channels: 4
          out_channels: 1
          img_size: [128, 128, 128]
          feature_size: 16
      - architecture: "swinunetr"
        checkpoint: "./outputs/swinunetr/checkpoints/best_model.pth"
        params:
          in_channels: 4
          out_channels: 1
          img_size: [128, 128, 128]
          feature_size: 48
    ensemble_method: "mean"
    weights: [0.5, 0.5]

inference:
  sliding_window_size: [128, 128, 128]
  overlap: 0.5
  use_test_time_augmentation: true
  batch_size: 4
  
  postprocessing:
    threshold: 0.5
    remove_small_objects: true
    min_size: 100
    fill_holes: true
    max_hole_size: 50
    largest_cc_only: false